apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-devops
  template:
    metadata:
      labels:
        app: demo-devops
    spec:
      containers:
      - name: demo-devops
        image: ketan897654/demo_devops:latest
        ports:
        - containerPort: 8057

        
---
apiVersion: v1
kind: Service
metadata:
  name: demo-devops-service
spec:
  selector:
    app: demo-devops
  ports:
    - protocol: TCP
      port: 8057
      targetPort: 8057
  type: NodePort